import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  container: { flex: 1, flexDirection: "column", backgroundColor: "#0f172a" },

  loading: { flex: 1, backgroundColor: "#0f172a", alignItems: "center", justifyContent: "center" },
  loadingText: { color: "#fff", fontSize: 22, fontWeight: "700" },

  photoArea: { height: 220, backgroundColor: "#1e293b", flexShrink: 0, overflow: "hidden" },
  photo: { width: "100%", height: "100%", resizeMode: "cover" },
  photoPlaceholder: { flex: 1, alignItems: "center", justifyContent: "center" },
  photoEmoji: { fontSize: 90 },

  orderStatusBadge: { position: "absolute", top: 14, right: 14, backgroundColor: "#f97316", borderRadius: 14, paddingHorizontal: 14, paddingVertical: 8, shadowColor: "#000", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 6 },
  orderStatusBadgeText: { color: "#fff", fontSize: 20, fontWeight: "900", textAlign: "center", lineHeight: 24 },

  /* 카드 + 떠 있는 화살표 컨테이너 */
  carouselOuter: { flex: 1, minHeight: 0, overflow: "hidden" },
  carouselClip: { flex: 1, minHeight: 0, overflow: "hidden", zIndex: 0 },
  // 옵션 유무와 상관없이 항상 위쪽 정렬 — 좌우 이동 버튼(추가 버튼 근처 고정)과
  // 위치가 어긋나지 않도록 카드가 늘 같은 자리에서 시작하게 한다
  slide: { height: "100%", alignItems: "center", justifyContent: "flex-start", paddingVertical: 6, paddingHorizontal: 16 },

  card: { backgroundColor: "#fff", borderRadius: 28, paddingVertical: 22, paddingHorizontal: 28, width: "100%", flexDirection: "column", gap: 8, shadowColor: "#000", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.35, shadowRadius: 24, elevation: 12 },
  cardWithOptions: { height: "100%", flexShrink: 1 },
  menuName: { fontSize: 40, fontWeight: "900", color: "#0f172a", lineHeight: 48 },
  menuQty: { fontSize: 28, fontWeight: "800", color: "#94a3b8" },
  menuQtyActive: { color: "#f59e0b" },
  price: { fontSize: 48, fontWeight: "900", color: "#1d4ed8", textAlign: "center" },

  optionsScroll: { flex: 1, marginTop: 10 },
  optionsScrollContent: { paddingBottom: 12, gap: 14 },
  optionGroupBlock: { gap: 8 },
  optionGroupLabelRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  optionGroupLabel: { fontSize: 24, fontWeight: "900", color: "#0f172a" },
  optionRequiredBadge: { backgroundColor: "#fee2e2", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 3 },
  optionRequiredText: { fontSize: 15, fontWeight: "800", color: "#ef4444" },
  optionChoiceRow: { flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 2, borderColor: "#e2e8f0", borderRadius: 16, paddingVertical: 14, paddingHorizontal: 16 },
  optionChoiceRowActive: { borderColor: "#1d4ed8", backgroundColor: "#eff6ff" },
  optionCheckCircle: { width: 32, height: 32, borderRadius: 16, borderWidth: 3, borderColor: "#cbd5e1", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  optionCheckCircleActive: { borderColor: "#1d4ed8", backgroundColor: "#1d4ed8" },
  optionCheckMark: { color: "#fff", fontSize: 18, fontWeight: "900" },
  optionChoiceName: { flex: 1, fontSize: 22, fontWeight: "700", color: "#334155" },
  optionChoiceNameActive: { color: "#0f172a", fontWeight: "900" },
  optionChoicePrice: { fontSize: 20, fontWeight: "800", color: "#1d4ed8" },

  addBtn: { width: "100%", paddingVertical: 22, backgroundColor: "#0f172a", borderRadius: 20, alignItems: "center", justifyContent: "center", marginTop: 4 },
  addBtnText: { color: "#fff", fontSize: 30, fontWeight: "900" },

  qtyRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#f1f5f9", borderRadius: 44, paddingHorizontal: 6, paddingVertical: 4, alignSelf: "stretch", justifyContent: "space-between", marginTop: 4 },
  qtyBtn: { width: 64, height: 64, alignItems: "center", justifyContent: "center" },
  qtyBtnText: { fontSize: 40, fontWeight: "700", color: "#0f172a" },
  qtyNum: { fontSize: 36, fontWeight: "900", color: "#0f172a", minWidth: 44, textAlign: "center" },

  /* 떠 있는 화살표 — 카드 위에 오버레이. 옵션이 길어져 카드가 늘어나도
     "추가"/수량 버튼 근처에 고정되도록 위에서부터 고정 위치로 둔다 */
  prevBtn: { position: "absolute", left: 4, top: 128, width: 60, height: 52, alignItems: "center", justifyContent: "center", zIndex: 20 },
  nextBtn: { position: "absolute", right: 4, top: 128, width: 60, height: 52, alignItems: "center", justifyContent: "center", zIndex: 20 },
  navArrow: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#f59e0b", alignItems: "center", justifyContent: "center", shadowColor: "#f59e0b", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.7, shadowRadius: 12, elevation: 10 },
  navArrowText: { fontSize: 30, fontWeight: "900", color: "#fff", lineHeight: 34 },

  bubble: { position: "absolute", right: 4, top: 62, width: 120, alignItems: "center", zIndex: 30 },
  bubbleBox: { backgroundColor: "#f59e0b", borderRadius: 14, paddingHorizontal: 14, paddingVertical: 10 },
  bubbleText: { color: "#fff", fontSize: 15, fontWeight: "900", textAlign: "center", lineHeight: 22 },

  dots: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, paddingVertical: 6, flexShrink: 0 },
  dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "rgba(255,255,255,0.2)" },
  dotActive: { width: 28, borderRadius: 5, backgroundColor: "#f59e0b" },

  cartBar: { backgroundColor: "#0f172a", padding: 16, paddingBottom: 20, flexDirection: "row", alignItems: "center", gap: 12, flexShrink: 0, borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.06)" },
  cartBadge: { backgroundColor: "#f59e0b", borderRadius: 10, paddingHorizontal: 14, paddingVertical: 7 },
  cartBadgeText: { color: "#fff", fontSize: 18, fontWeight: "900" },
  cartText: { color: "#fff", fontSize: 20, fontWeight: "700", flex: 1 },
  cartPrice: { color: "#f59e0b", fontSize: 24, fontWeight: "900" },

  modalOverlay: { justifyContent: "flex-end", zIndex: 200 },
  modalBg: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.5)" },
  modalSheet: { backgroundColor: "#fff", borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 28, paddingTop: 14, paddingBottom: 22, maxHeight: "80%" },
  modalTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 },
  modalTitleLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  modalTitle: { fontSize: 26, fontWeight: "900", color: "#0f172a" },
  modalTitleTypeText: { fontSize: 16, fontWeight: "800" },
  modalTitleActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  tossLogo: { backgroundColor: "#0064FF", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  tossLogoText: { color: "#fff", fontSize: 16, fontWeight: "900", letterSpacing: -0.5 },
  trashBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#fee2e2", alignItems: "center", justifyContent: "center" },
  trashBtnIcon: { fontSize: 22 },
  closeBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#f1f5f9", alignItems: "center", justifyContent: "center" },
  closeBtnText: { fontSize: 18, fontWeight: "900", color: "#64748b" },
  modalList: { flexShrink: 1, marginBottom: 20 },
  modalItem: { flexDirection: "column", paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: "#e2e8f0", gap: 10 },
  modalItemHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  modalItemName: { flex: 1, fontSize: 22, fontWeight: "800", color: "#0f172a" },
  modalItemOptions: { fontSize: 17, fontWeight: "700", color: "#64748b" },
  deleteBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: "#fee2e2", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  deleteBtnText: { fontSize: 16, fontWeight: "900", color: "#ef4444" },
  modalItemBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  modalItemPrice: { fontSize: 22, fontWeight: "900", color: "#1d4ed8" },

  payPhoneField: { paddingTop: 10, paddingBottom: 4, borderTopWidth: 2, borderTopColor: "#e2e8f0", gap: 8 },
  payPhoneLabel: { fontSize: 19, fontWeight: "800", color: "#334155" },
  payPhoneRow: { flexDirection: "row", alignItems: "center", gap: 10, minWidth: 0 },
  payPhoneInputFront: { width: 90, flexShrink: 0, textAlign: "center", borderWidth: 2, borderColor: "#cbd5e1", borderRadius: 14, paddingHorizontal: 10, paddingVertical: 14, fontSize: 22, fontWeight: "700", color: "#0f172a", backgroundColor: "#fff" },
  payPhoneInputBack: { flex: 1, minWidth: 0, borderWidth: 2, borderColor: "#cbd5e1", borderRadius: 14, paddingHorizontal: 14, paddingVertical: 14, fontSize: 22, fontWeight: "700", color: "#0f172a", backgroundColor: "#fff" },
  payPhoneSep: { fontSize: 22, fontWeight: "800", color: "#94a3b8" },
  payPhoneInputError: { borderColor: "#ef4444" },
  payPhoneErrorText: { fontSize: 16, color: "#ef4444", fontWeight: "700" },

  statusOrderBlock: { gap: 4, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  statusHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 },
  statusStateBadge: { backgroundColor: "#94a3b8", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  statusStateBadgeText: { fontSize: 15, fontWeight: "800", color: "#fff" },
  statusReceived: { backgroundColor: "#94a3b8" },
  statusPreparing: { backgroundColor: "#f59e0b" },
  statusReady: { backgroundColor: "#22c55e" },
  statusPickupText: { fontSize: 17, fontWeight: "800", color: "#1d4ed8", marginTop: 4 },

  pendingSection: { marginTop: 8, paddingTop: 8, borderTopWidth: 2, borderTopColor: "#e2e8f0", gap: 10 },
  pendingSectionTitle: { fontSize: 18, fontWeight: "800", color: "#94a3b8" },
  pendingOrderBlock: { gap: 4, paddingVertical: 4 },
  pendingOrderBadgeRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 4 },
  pendingOrderBadge: { alignSelf: "flex-start", backgroundColor: "#f97316", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  pendingOrderBadgeText: { fontSize: 15, fontWeight: "800", color: "#fff" },
  pendingItemRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  pendingItemName: { flex: 1, fontSize: 19, fontWeight: "700", color: "#334155" },
  pendingItemQty: { fontSize: 19, fontWeight: "800", color: "#64748b" },

  cancelRadioOuter: { width: 30, height: 30, borderRadius: 15, borderWidth: 3, borderColor: "#cbd5e1", alignItems: "center", justifyContent: "center" },
  cancelRadioOuterActive: { borderColor: "#ef4444" },
  cancelRadioOuterDisabled: { borderColor: "#e2e8f0", backgroundColor: "#f1f5f9", opacity: 0.6 },
  cancelRadioInner: { width: 16, height: 16, borderRadius: 8, backgroundColor: "#ef4444" },

  modalFooter: { paddingTop: 9, borderTopWidth: 2, borderTopColor: "#e2e8f0", gap: 14 },
  modalTotal: { fontSize: 24, fontWeight: "900", color: "#0f172a", textAlign: "center" },
  modalBtnCol: { gap: 12 },
  modalOrderBtnDisabled: { opacity: 0.4 },
  modalOrderOnlyBtn: { borderWidth: 2, borderColor: "#0f172a", borderRadius: 18, paddingVertical: 18, alignItems: "center" },
  modalOrderOnlyBtnText: { color: "#0f172a", fontSize: 22, fontWeight: "900" },
  modalOrderOnlyBtnCancel: { borderColor: "#ef4444" },
  modalOrderOnlyBtnTextCancel: { color: "#ef4444" },
  modalPayBtn: { backgroundColor: "#0f172a", borderRadius: 18, paddingVertical: 10, alignItems: "center" },
  modalPayBtnText: { color: "#fff", fontSize: 24, fontWeight: "900" },

  confirmOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", alignItems: "center", zIndex: 300 },
  confirmBox: { backgroundColor: "#fff", borderRadius: 28, padding: 28, alignItems: "center", width: 320, shadowColor: "#000", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.2, shadowRadius: 20, elevation: 20 },
  confirmEmoji: { fontSize: 40, marginBottom: 10 },
  confirmTitle: { fontSize: 26, fontWeight: "900", color: "#0f172a", marginBottom: 6 },
  confirmMsg: { fontSize: 19, color: "#64748b", marginBottom: 22, textAlign: "center" },
  confirmBtns: { flexDirection: "row", gap: 12, width: "100%" },
  confirmCancelBtn: { flex: 1, borderWidth: 2, borderColor: "#e2e8f0", borderRadius: 16, paddingVertical: 16, alignItems: "center" },
  confirmCancelText: { fontSize: 19, fontWeight: "700", color: "#64748b" },
  confirmOkBtn: { flex: 1, backgroundColor: "#ef4444", borderRadius: 16, paddingVertical: 16, alignItems: "center" },
  confirmOkText: { fontSize: 19, fontWeight: "800", color: "#fff" },
});
