import { StyleSheet } from "react-native";
import { colors, radius, font, spacing } from "./theme";

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bgLight, flexDirection: "column", overflow: "hidden" },

  shopBanner: { backgroundColor: colors.bgCard, padding: spacing["4"], borderBottomWidth: 1, borderBottomColor: colors.borderLight, flexShrink: 0 },
  shopNameRow: { flexDirection: "row", alignItems: "center", gap: spacing["2.5"], marginBottom: spacing["1.5"] },
  shopName: { fontSize: font["5xl"], fontWeight: "900", color: colors.text },
  shopAiBadge: { fontSize: font.sm, color: colors.accent, fontWeight: "800" },
  tableBadge: { backgroundColor: colors.accent, borderRadius: radius.sm, paddingHorizontal: spacing["2.5"], paddingVertical: spacing["1"] },
  tableBadgeText: { color: colors.white, fontSize: font.md, fontWeight: "900", letterSpacing: 1 },
  scanListBtn: { marginLeft: "auto", borderWidth: 1.5, borderColor: colors.green, borderRadius: radius["2xl"], paddingHorizontal: spacing["2.5"], paddingVertical: spacing["1"], backgroundColor: colors.greenPaleBg2 },
  scanListBtnText: { fontSize: font.sm, fontWeight: "700", color: colors.green },

  paymentHistoryBtn: { borderWidth: 1.5, borderColor: colors.accent, borderRadius: radius["2xl"], paddingHorizontal: spacing["2.5"], paddingVertical: spacing["1"], backgroundColor: colors.accentLight },
  paymentHistoryBtnText: { fontSize: font.sm, fontWeight: "700", color: colors.accent },

  chatFab: { height: spacing["12"], borderRadius: radius["4xl"], backgroundColor: colors.primary, justifyContent: "center", alignItems: "center", paddingHorizontal: spacing["5"], shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 10, elevation: 8 },
  chatFabText: { fontSize: font.lg, fontWeight: "800", color: colors.white },

  aiToast: { position: "absolute", bottom: 196, right: spacing["5"], backgroundColor: colors.primary, borderRadius: radius["3xl"], paddingHorizontal: spacing["3.5"], paddingVertical: spacing["2"], shadowColor: colors.black, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 10 },
  aiToastText: { color: colors.white, fontSize: font.md, fontWeight: "700" },
  shopMeta: { flexDirection: "row", alignItems: "center", gap: spacing["2"], marginBottom: spacing["2.5"] },
  shopRating: { fontSize: font.md, fontWeight: "700", color: colors.text },
  star: { color: colors.accent },
  shopInfo: { fontSize: font.base, color: colors.textMuted },
  shopTags: { flexDirection: "row", gap: spacing["2"], marginBottom: spacing["2"], flexWrap: "wrap", alignItems: "stretch" },
  shopTag: { flexDirection: "row", alignItems: "center", gap: spacing["1"], backgroundColor: colors.slate100, borderRadius: radius.pill, paddingHorizontal: spacing["2.5"], paddingVertical: 5 },
  orderTypeGroup: { flexDirection: "row", alignItems: "center", backgroundColor: colors.slate100, borderRadius: radius.pill, overflow: "hidden" },
  orderTypeBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing["1"], paddingHorizontal: spacing["2.5"], paddingVertical: 5 },
  orderTypeBtnLeft: { borderRightWidth: 1, borderRightColor: colors.borderMedium },
  orderTypeBtnRight: {},
  orderTypeBtnActive: { backgroundColor: colors.primary },
  shopTagActive: { backgroundColor: colors.primary },
  shopTagIcon: { fontSize: font.base },
  orderTypeIconWrap: { width: 18, height: 18, borderRadius: 9, justifyContent: "center", alignItems: "center" },
  orderTypeIconDineIn: { backgroundColor: colors.green },
  orderTypeIconTakeout: { backgroundColor: colors.accent },
  orderTypeIconText: { fontSize: 10 },
  shopTagText: { fontSize: font.sm, fontWeight: "700", color: colors.slate600 },
  shopTagTextDineIn: { color: colors.green },
  shopTagTextTakeout: { color: colors.accent },
  shopTagTextActive: { color: colors.white },
  seatBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: "transparent", borderRadius: radius.pill, borderWidth: 1.5, borderColor: colors.indigoLight, paddingHorizontal: spacing["2.5"], paddingVertical: 5 },
  seatBtnText: { fontSize: font.sm, fontWeight: "700", color: colors.indigo },
  bizAddr: { fontSize: font.base, color: colors.textMuted, marginTop: 2 },

  orderStatusBar: { backgroundColor: colors.accentLight, borderRadius: radius.lg, marginHorizontal: spacing["3"], marginTop: spacing["2"], marginBottom: spacing["2"], paddingHorizontal: spacing["4"], paddingVertical: spacing["3.5"] },
  orderStatusBarTitle: { fontSize: font.xl, fontWeight: "800", color: colors.textGray, marginBottom: spacing["2.5"] },
  orderStatusRow: { marginBottom: spacing["2.5"] },
  orderStatusHeaderRow: { flexDirection: "row", alignItems: "center", gap: spacing["2.5"], marginBottom: spacing["1.5"] },
  orderStatusOrderBadge: { backgroundColor: colors.black, borderRadius: radius.sm, paddingHorizontal: spacing["2.5"], paddingVertical: 3 },
  orderStatusOrderBadgeText: { fontSize: font.md, fontWeight: "800", color: colors.white },
  orderStatusSummaryLink: { fontSize: font.md, fontWeight: "400", color: colors.textSecondary, textDecorationLine: "underline" },
  orderStatusSteps: { flexDirection: "row", alignItems: "center" },
  orderStatusStepWrap: { flexDirection: "row", alignItems: "center", flex: 1 },
  orderStatusDot: { width: 13, height: 13, borderRadius: 999, backgroundColor: colors.slate300 },
  orderStatusDotActive: { backgroundColor: colors.accent },
  orderStatusStepText: { fontSize: font.md, fontWeight: "700", color: colors.textFaint, marginLeft: spacing["1.5"] },
  orderStatusStepTextActive: { color: colors.accent },
  orderStatusLineWrap: { flex: 1, flexDirection: "row", alignItems: "center", marginHorizontal: spacing["1.5"] },
  orderStatusLine: { flex: 1, height: 3, backgroundColor: colors.slate300 },
  orderStatusLineActive: { backgroundColor: colors.accent },
  orderStatusArrowHead: {
    width: 0,
    height: 0,
    marginLeft: -1,
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderLeftWidth: 7,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: colors.slate300,
  },
  orderStatusArrowHeadActive: { borderLeftColor: colors.accent },

  orderDetailPopupBox: { backgroundColor: colors.bgCard, borderRadius: radius["3xl"], padding: spacing["5"], width: 300, maxHeight: 420, shadowColor: colors.black, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.15, shadowRadius: 20, elevation: 20 },
  orderDetailPopupTitle: { fontSize: font.lg, fontWeight: "900", color: colors.text, marginBottom: spacing["3"] },
  orderDetailPopupRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: spacing["2.5"] },
  orderDetailPopupMenuName: { fontSize: font.base, fontWeight: "700", color: colors.text },
  orderDetailPopupOption: { fontSize: font.sm, color: colors.textMuted, marginTop: 2 },
  orderDetailPopupPrice: { fontSize: font.base, fontWeight: "700", color: colors.text, marginLeft: spacing["2"] },
  orderDetailPopupTotalRow: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: colors.borderLight, paddingTop: spacing["2.5"], marginTop: spacing["1"] },
  orderDetailPopupTotalLabel: { fontSize: font.base, fontWeight: "800", color: colors.textGray },
  orderDetailPopupTotalValue: { fontSize: font.base, fontWeight: "900", color: colors.accent },
  orderDetailPopupCloseBtn: { marginTop: spacing["4"], backgroundColor: colors.primary, borderRadius: radius.lg, paddingVertical: spacing["2.5"], alignItems: "center" },
  orderDetailPopupCloseBtnText: { fontSize: font.base, fontWeight: "800", color: colors.white },

  catBar: { backgroundColor: colors.bgCard, borderBottomWidth: 1, borderBottomColor: colors.borderLight, flexShrink: 0, flexDirection: "row", paddingHorizontal: spacing["1"] },
  catItem: { paddingHorizontal: spacing["3"], paddingVertical: 11, position: "relative" },
  catText: { fontSize: font.md, fontWeight: "700", color: colors.textFaint },
  catTextActive: { color: colors.text },
  catIndicator: { position: "absolute", bottom: 0, left: 0, right: 0, height: 2, backgroundColor: colors.text },

  list: { flex: 1 },
  listContent: { paddingTop: spacing["2"], paddingBottom: 220 },

  card: { backgroundColor: colors.bgCard, flexDirection: "row", padding: spacing["4"], gap: spacing["3.5"], borderBottomWidth: 1, borderBottomColor: colors.bgLight },
  imgWrap: { position: "relative" },
  img: { width: 90, height: 90, borderRadius: radius.lg, backgroundColor: "#eee" },
  noImg: { backgroundColor: colors.bgInput, justifyContent: "center", alignItems: "center" },
  noImgText: { fontSize: font.xs, color: colors.textFaint, fontWeight: "600" },
  badge: { position: "absolute", top: spacing["1.5"], left: spacing["1.5"], backgroundColor: colors.accent, borderRadius: radius.xs, paddingHorizontal: 7, paddingVertical: 2 },
  badgeText: { color: colors.white, fontSize: font["2xs"], fontWeight: "800" },
  info: { flex: 1 },
  name: { fontSize: font.xl, fontWeight: "800", color: colors.text, marginBottom: spacing["1"] },
  desc: { fontSize: font.base, color: colors.textMuted, lineHeight: 17, marginBottom: spacing["2.5"] },
  cardBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  price: { fontSize: font["2xl"], fontWeight: "900", color: colors.text },

  addBtn: { width: spacing["8"], height: spacing["8"], backgroundColor: colors.text, borderRadius: radius["2xl"], justifyContent: "center", alignItems: "center" },
  addBtnText: { color: colors.white, fontSize: font["6xl"], fontWeight: "300", lineHeight: 22 },

  qtyRow: { flexDirection: "row", alignItems: "center", gap: spacing["1.5"], backgroundColor: colors.bgInput, borderRadius: radius.pill, paddingHorizontal: spacing["1"], paddingVertical: 2 },
  qtyBtn: { width: spacing["7"], height: spacing["7"], justifyContent: "center", alignItems: "center" },
  qtyBtnText: { fontSize: font["4xl"], fontWeight: "700", color: colors.text },
  qtyNum: { fontSize: font.lg, fontWeight: "800", color: colors.text, minWidth: 20, textAlign: "center" },

  callBar: { padding: spacing["4"] },
  callBtn: { borderWidth: 1.5, borderColor: colors.border, borderRadius: radius.lg, padding: 13, alignItems: "center" },
  callBtnDisabled: { opacity: 0.4 },
  callBtnText: { color: colors.textGray, fontSize: font.lg, fontWeight: "700" },

  /* 장바구니 바 */
  cartBar: { flexShrink: 0, backgroundColor: colors.text, flexDirection: "row", alignItems: "center", paddingHorizontal: spacing["4.5"], paddingVertical: 14, gap: spacing["2.5"] },
  cartBadge: { backgroundColor: colors.accent, borderRadius: radius.lg, paddingHorizontal: spacing["2"], paddingVertical: 2 },
  cartBadgeText: { color: colors.white, fontSize: font.base, fontWeight: "800" },
  cartBarCenter: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing["2"] },
  cartBarText: { color: colors.white, fontSize: font.xl, fontWeight: "700" },
  cartOrderTypeBadge: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing["2"], paddingVertical: 3 },
  cartOrderTypeText: { color: colors.white, fontSize: font.sm, fontWeight: "700" },
  cartBarTotal: { color: colors.accent, fontSize: font.xl, fontWeight: "900" },

  /* 팝업 오버레이 */
  overlay: { flex: 1, justifyContent: "flex-end" },
  overlayBg: { ...StyleSheet.absoluteFillObject, backgroundColor: colors.overlayDark },
  sheet: { backgroundColor: colors.bgCard, borderTopLeftRadius: radius["3xl"], borderTopRightRadius: radius["3xl"], maxHeight: "75%", overflow: "hidden" },

  sheetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: spacing["4.5"], borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  sheetTitle: { fontSize: font["3xl"], fontWeight: "900", color: colors.text },
  closeBtn: { width: spacing["8"], height: spacing["8"], backgroundColor: colors.bgInput, borderRadius: radius["2xl"], justifyContent: "center", alignItems: "center" },
  closeBtnText: { fontSize: font.md, color: colors.textGray, fontWeight: "700" },
  trashBtn: { width: spacing["8"], height: spacing["8"], backgroundColor: "#fff1f2", borderRadius: radius["2xl"], justifyContent: "center", alignItems: "center" },
  trashBtnText: { fontSize: font.xl },

  confirmOverlay: { flex: 1, backgroundColor: colors.overlayDark, justifyContent: "center", alignItems: "center" },
  confirmBox: { backgroundColor: colors.bgCard, borderRadius: radius["3xl"], padding: spacing["7"], alignItems: "center", width: 280, shadowColor: colors.black, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.15, shadowRadius: 20, elevation: 20 },
  confirmEmoji: { fontSize: 36, marginBottom: spacing["3"] },
  confirmTitle: { fontSize: font["3xl"], fontWeight: "900", color: colors.text, marginBottom: spacing["1.5"] },
  confirmMsg: { fontSize: font.lg, color: colors.textMuted, marginBottom: spacing["6"], textAlign: "center" },
  confirmBtns: { flexDirection: "row", gap: spacing["2.5"], width: "100%" },
  confirmCancelBtn: { flex: 1, borderWidth: 1.5, borderColor: colors.border, borderRadius: radius.lg, paddingVertical: spacing["3"], alignItems: "center" },
  confirmCancelText: { fontSize: font.lg, fontWeight: "700", color: colors.textMuted },
  confirmOkBtn: { flex: 1, backgroundColor: colors.red, borderRadius: radius.lg, paddingVertical: spacing["3"], alignItems: "center" },
  confirmOkText: { fontSize: font.lg, fontWeight: "800", color: colors.white },

  checkoutHint: { backgroundColor: colors.accentLight, paddingVertical: spacing["2.5"], paddingHorizontal: spacing["4.5"], borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  checkoutHintText: { fontSize: font.md, fontWeight: "700", color: colors.accent, textAlign: "center" },

  sheetList: { flexShrink: 1 },
  cartItem: { flexDirection: "row", alignItems: "center", padding: spacing["3.5"], gap: spacing["3"], borderBottomWidth: 1, borderBottomColor: colors.bgLight },
  cartItemImg: { width: 56, height: 56, borderRadius: radius.md, backgroundColor: "#eee" },
  cartItemInfo: { flex: 1 },
  cartItemName: { fontSize: font.lg, fontWeight: "700", color: colors.text, marginBottom: spacing["1"] },
  cartItemOptions: { fontSize: font.sm, color: colors.textGrayAlt, fontWeight: "600", marginBottom: spacing["1"] },
  cartItemBreakdown: { fontSize: font.sm, color: colors.textLight, fontWeight: "600", marginBottom: spacing["1"] },
  cartItemPrice: { fontSize: font.md, fontWeight: "800", color: colors.accent },
  cartItemEdit: { fontSize: font.sm, color: colors.green, fontWeight: "700", marginTop: spacing["1"], textDecorationLine: "underline" },

  successSheet: { backgroundColor: colors.bgCard, borderRadius: radius["4xl"], padding: spacing["8"], alignItems: "center", margin: spacing["8"] },
  successEmoji: { fontSize: 60, marginBottom: spacing["3"] },
  successTitle: { fontSize: font["8xl"], fontWeight: "900", color: colors.text, marginBottom: spacing["2"] },
  successDesc: { fontSize: font.lg, color: colors.textMuted, textAlign: "center", lineHeight: 24, marginBottom: spacing["6"] },
  successBank: { fontSize: font.xl, fontWeight: "800", color: colors.text },
  successNote: { fontSize: font.md, fontWeight: "800", color: colors.accent },
  successBtn: { backgroundColor: colors.text, borderRadius: radius.xl, paddingHorizontal: spacing["12"], paddingVertical: 14 },
  successBtnText: { color: colors.white, fontSize: font["2xl"], fontWeight: "800" },

  /* 결제 모달 */
  paySheet: { backgroundColor: colors.bgBase, borderTopLeftRadius: radius["4xl"], borderTopRightRadius: radius["4xl"], maxHeight: "85%", overflow: "hidden" },
  payHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: spacing["5"], backgroundColor: colors.bgCard, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  payHeaderLeft: { flexDirection: "row", alignItems: "center", gap: spacing["2.5"] },
  tossLogo: { backgroundColor: colors.tossBlue, borderRadius: radius.sm, paddingHorizontal: 9, paddingVertical: spacing["1"] },
  tossLogoText: { color: colors.white, fontSize: font.md, fontWeight: "900", letterSpacing: -0.5 },
  payHeaderTitle: { fontSize: font["4xl"], fontWeight: "900", color: colors.text },

  paySection: { backgroundColor: colors.bgCard, borderRadius: radius["2xl"], padding: spacing["4"], gap: spacing["2.5"], marginBottom: spacing["3"], borderWidth: 1.5, borderColor: "transparent" },
  paySectionCurrent: { backgroundColor: colors.accentLight, borderColor: colors.accent },
  paySectionPending: { backgroundColor: colors.slate100, borderColor: colors.borderMedium },
  paySectionTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  paySectionTitle: { fontSize: font.md, fontWeight: "800", color: colors.slate400, marginBottom: spacing["1"], textTransform: "uppercase", letterSpacing: 0.5 },
  paySectionTypText: { fontSize: font.sm, fontWeight: "700", color: colors.textSecondary },
  payOrderRow: { flexDirection: "row", alignItems: "center", gap: spacing["1"] },
  payOrderName: { flex: 1, fontSize: font.lg, fontWeight: "700", color: colors.textSecondary },
  payOrderQty: { fontSize: font.md, color: colors.slate400, fontWeight: "600", marginHorizontal: spacing["1"] },
  payOrderPrice: { fontSize: font.lg, fontWeight: "700", color: colors.textSecondary },
  payDivider: { height: 1, backgroundColor: colors.slate100, marginVertical: spacing["1"] },
  payTotalAmt: { fontSize: font["4xl"], fontWeight: "900", color: colors.primary },

  pendingOrderGroup: { marginTop: spacing["3"] },
  pendingOrderBadgeRow: { flexDirection: "row", alignItems: "center", gap: spacing["2"], marginBottom: spacing["1.5"] },
  pendingOrderBadge: { alignSelf: "flex-start", backgroundColor: colors.accent, borderRadius: radius.sm, paddingHorizontal: spacing["2"], paddingVertical: 3 },
  pendingOrderBadgeText: { fontSize: font.sm, fontWeight: "800", color: colors.white },
  pendingOrderTypText: { fontSize: font.sm, fontWeight: "700", color: colors.textSecondary, marginLeft: "auto" },

  payTossNote: { fontSize: font.base, color: colors.slate400, textAlign: "center", marginTop: spacing["4"], fontWeight: "600" },

  payFooter: { backgroundColor: colors.bgCard, padding: spacing["4"], borderTopWidth: 1, borderTopColor: colors.borderLight, gap: spacing["3"] },
  payAmtRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  payAmtLabel: { fontSize: font.lg, color: colors.slate500, fontWeight: "600" },
  payAmtValue: { fontSize: font["6xl"], fontWeight: "900", color: colors.primary },
  payBtn: { backgroundColor: colors.primary, borderRadius: radius["2xl"], paddingVertical: spacing["4"], alignItems: "center", gap: spacing["1"] },
  payBtnDisabled: { backgroundColor: colors.slate300, opacity: 0.6 },
  payBtnText: { color: colors.white, fontSize: font["2xl"], fontWeight: "900", letterSpacing: 0.3 },

  payBtnRow: { flexDirection: "row", gap: spacing["2.5"] },
  orderOnlyBtn: { flex: 1, backgroundColor: colors.bgCard, borderWidth: 1.5, borderColor: colors.primary, borderRadius: radius["2xl"], paddingVertical: spacing["3"], alignItems: "center", justifyContent: "center" },
  orderOnlyBtnDisabled: { borderColor: colors.slate300, opacity: 0.6 },
  orderOnlyBtnText: { color: colors.primary, fontSize: font.lg, fontWeight: "800" },
  payNowBtn: { flex: 1.4, backgroundColor: colors.primary, borderRadius: radius["2xl"], paddingVertical: spacing["3"], alignItems: "center", justifyContent: "center" },
  payNowBtnDisabled: { backgroundColor: colors.slate300, opacity: 0.6 },
  payNowBtnText: { color: colors.white, fontSize: font.xl, fontWeight: "900", letterSpacing: 0.3 },

  sheetFooter: { padding: spacing["4"], borderTopWidth: 1, borderTopColor: colors.borderLight },
  totalRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing["3"] },
  totalLabel: { fontSize: font.md, color: colors.textMuted, fontWeight: "600" },
  totalPrice: { fontSize: font["6xl"], fontWeight: "900", color: colors.text },
  orderBtn: { backgroundColor: colors.text, borderRadius: radius.xl, padding: 15, alignItems: "center" },
  orderBtnDisabled: { backgroundColor: colors.slate300, opacity: 0.6 },
  orderBtnText: { color: colors.white, fontSize: font.xl, fontWeight: "800" },
});
